[package]
name = "cas"
version = "0.1.0-dev.1"
authors = ["Jan Roman Cisowski „j-Cis”"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/j-Cis/tmp-nums"
# gh codespace ssh -c ideal-guide-96j7px56g6537jg
# gh codespace stop -c ideal-guide-96j7px56g6537jg

resolver = "3"

[lib]
name = "x"
path = "src/api.rs" 

# ==========================================
# Globalna konfiguracja lintów (Analiza kodu)
# ==========================================
[lints.rust]
# Kategorycznie zabraniamy używania bloków `unsafe` w całym projekcie
unsafe_code = "forbid"
# Ostrzegamy o nieużywanych importach, zmiennych i funkcjach
unused = "warn"

[lints.clippy]
# Włączamy surowsze reguły, ale jako ostrzeżenia (nie zepsują kompilacji)
pedantic = "warn"
# Możemy tu też wyciszyć globalnie to, co nas irytuje (opcjonalnie):
too_many_arguments = "allow"